spring:
  application:
    name: doseogateway
  cloud:
    gateway:
      default-filters:
        # 헤더의 중복을 제거하기 위한 필터
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://127.0.0.1:6060'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: user
          uri: http://127.0.0.1:7071
          predicates:
            - Path=/user/**

        - id: book
          uri: http://127.0.0.1:7072
          predicates:
            - Path=/book/**

        - id: rent
          uri: http://127.0.0.1:7073
          predicates:
            - Path=/rent/**


server:
  port: 7070

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://192.168.0.27:8761/eureka
      defaultZone: http://127.0.0.1:8761/eureka
